n, m = map(int, input().split())
a = set(list(map(int, input().split())))
b = set(list(map(int, input().split())))
giao = sorted(list(a & b))
hieu1 = sorted(list(a - b))
hieu2 = sorted(list(b - a))
for x in giao: print(x, end = ' ')
print()
for x in hieu1: print(x, end = ' ')
print()
for x in hieu2: print(x, end = ' ')
print()
